query($cursor: String, $viewerId: ID!) {
  viewer {
    repositories(
      first: 100,
      after: $cursor
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        name
        nameWithOwner
        isArchived
        description
        primaryLanguage {
          name
          color
        }
        defaultBranchRef {
            target {
                ... on Commit {
                    historyCommitCount: history(author: {id: $viewerId}) { totalCount }
                }
            }
        }
      }
    }
  }
}